from __future__ import annotations

import io
import json
import subprocess
from dataclasses import dataclass, field
from types import SimpleNamespace

import pytest
from upgrade.agent import AGENT, SCOPES

from day2_agents.audit import AuditLogger
from day2_agents.scopes import PermissionSet

REPO = "okaforpascal400/day2-control-plane"
PR = "23"
PR_URL = f"https://github.com/{REPO}/pull/{PR}"

PIP_DIFF = (
    "diff --git a/app/api/requirements.txt b/app/api/requirements.txt\n"
    "--- a/app/api/requirements.txt\n"
    "+++ b/app/api/requirements.txt\n"
    "@@ -1,3 +1,3 @@\n"
    "-fastapi==0.139.2\n"
    "+fastapi==0.140.0\n"
    " uvicorn[standard]==0.51.0\n"
)

# Renovate's real body shape: a table, then a collapsible release-notes block.
RENOVATE_BODY = """\
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| fastapi | dependencies | minor | `0.139.2` -> `0.140.0` |

---

<details>
<summary>Release Notes for fastapi/fastapi</summary>

### v0.140.0

* **Breaking**: `Depends` no longer caches by default.
* Added `response_model_exclude_defaults`.

</details>

---

This PR was generated by Mend Renovate.
"""


@dataclass
class FakeRunner:
    results: dict[str, subprocess.CompletedProcess] = field(default_factory=dict)
    calls: list[list[str]] = field(default_factory=list)
    stdins: list[str | None] = field(default_factory=list)

    def __call__(self, argv, stdin, cwd):
        argv = list(argv)
        self.calls.append(argv)
        self.stdins.append(stdin)
        joined = " ".join(argv)
        for key, result in self.results.items():
            if key in joined:
                return result
        return subprocess.CompletedProcess(argv, 0, "", "")

    def ran(self, *fragment: str) -> bool:
        return any(all(f in " ".join(c) for f in fragment) for c in self.calls)

    def comment_body(self) -> str:
        for call, stdin in zip(self.calls, self.stdins, strict=True):
            if "comments" in " ".join(call) and stdin:
                return json.loads(stdin)["body"]
        return ""


def ok(stdout: str = "") -> subprocess.CompletedProcess:
    return subprocess.CompletedProcess([], 0, stdout, "")


def gh_runner(
    author: str = "renovate[bot]",
    head_ref: str = "renovate/fastapi-0.x",
    body: str = RENOVATE_BODY,
    diff: str = PIP_DIFF,
    title: str = "chore(deps): update dependency fastapi to v0.140.0",
) -> FakeRunner:
    runner = FakeRunner()
    # `gh api repos/<repo>/pulls/<n>` — metadata. The diff request hits the same
    # path with an Accept header, so it is keyed on that header instead.
    runner.results["Accept: application/vnd.github.diff"] = ok(diff)
    runner.results[f"pulls/{PR}"] = ok(
        json.dumps(
            {
                "number": int(PR),
                "title": title,
                "body": body,
                "html_url": PR_URL,
                "user": {"login": author},
                "head": {"ref": head_ref},
            }
        )
    )
    runner.results["comments"] = ok(json.dumps({"html_url": f"{PR_URL}#issuecomment-1"}))
    return runner


class FakeClaude:
    def __init__(self, payload: dict | str, stop_reason: str = "end_turn"):
        text = payload if isinstance(payload, str) else json.dumps(payload)
        self.prompts: list[dict] = []
        outer = self

        class Messages:
            def create(self, **kwargs):
                outer.prompts.append(kwargs)
                return SimpleNamespace(
                    content=[SimpleNamespace(type="text", text=text)],
                    model="claude-opus-5",
                    stop_reason=stop_reason,
                    usage=SimpleNamespace(
                        input_tokens=8000,
                        output_tokens=1200,
                        cache_creation_input_tokens=0,
                        cache_read_input_tokens=0,
                    ),
                    _request_id="req_fake",
                )

        self.messages = Messages()


@pytest.fixture
def audit(tmp_path) -> AuditLogger:
    return AuditLogger(AGENT, "pytest", tmp_path / "audit.jsonl", io.StringIO())


@pytest.fixture
def scopes() -> PermissionSet:
    return PermissionSet.declare(AGENT, SCOPES)


def annotation_payload(**overrides) -> dict:
    payload = {
        "risk": "high",
        "risk_reason": "0.140.0 removes Depends caching by default, and "
        "app/api/api/deps.py relies on a cached dependency for the session.",
        "upstream_changes": "Depends no longer caches by default; a new "
        "response_model_exclude_defaults option was added.",
        "our_usage": "app/api/api/deps.py declares the DB session dependency; "
        "every route module imports it.",
        "affected_paths": ["app/api/api/deps.py"],
        "breaking_changes": ["Depends no longer caches by default"],
        "recommendation": "review",
        "recommended_action": "Read app/api/api/deps.py and confirm the "
        "session dependency does not depend on per-request caching.",
        "confidence": "high",
        "confidence_reason": "The release notes and our usage were both shown.",
    }
    payload.update(overrides)
    return payload
